;;; config-perforce.el --- Explicit asynchronous P4 commands -*- lexical-binding: t; -*-
(require 'config-core)
;; p4 discovers this name upward from each process working directory.
(unless (getenv "P4CONFIG") (setenv "P4CONFIG" ".p4config"))
(unless (getenv "P4IGNORE") (setenv "P4IGNORE" ".p4ignore.txt"))
(defun my-p4-file ()
  (unless buffer-file-name (user-error "No visited file"))
  (when (file-remote-p buffer-file-name) (user-error "Local Windows files only"))
  ;; P4 filespec escaping is independent of shell quoting.
  (let ((file (expand-file-name buffer-file-name)))
    (dolist (pair '(("%" . "%25") ("#" . "%23") ("@" . "%40") ("\\*" . "%2A")))
      (setq file (replace-regexp-in-string (car pair) (cdr pair) file t t)))
    file))
(defun my-p4-edit ()
  (interactive)
  (let* ((file (my-p4-file)) (buffer (current-buffer))
         (default-directory (file-name-directory buffer-file-name))
         (output (generate-new-buffer "*p4 edit*")))
    (make-process
     :name "p4-edit" :buffer output :noquery t :connection-type 'pipe
     :command (list (my-executable "p4") "edit" file)
     :sentinel (lambda (process _event)
                 (when (eq (process-status process) 'exit)
                   (if (zerop (process-exit-status process))
                       (when (buffer-live-p buffer)
                         (with-current-buffer buffer
                           (setq buffer-read-only (not (file-writable-p buffer-file-name))))
                         (message "p4 edit complete"))
                     (display-buffer output)))))))
(defun my-p4-revert ()
  "Revert the disk file only after explicit confirmation."
  (interactive)
  (let ((file (my-p4-file)))
    (when (buffer-modified-p) (user-error "Save or discard buffer edits before p4 revert"))
    (when (yes-or-no-p "Discard this file's workspace changes with p4 revert? ")
      (my-process-output "p4 revert" (my-executable "p4") (list "revert" file)
                         (file-name-directory buffer-file-name)))))
(defun my-p4-opened ()
  (interactive) (my-process-output "p4 opened" (my-executable "p4") '("opened") (my-project-root)))
(defun my-p4-diff ()
  (interactive)
  (when (buffer-modified-p) (user-error "Save first; p4 diff reads the disk file"))
  (my-process-output "p4 diff" (my-executable "p4") (list "diff" "-du" (my-p4-file))
                     (file-name-directory buffer-file-name)))
(defun my-p4-info ()
  (interactive) (my-process-output "p4 info" (my-executable "p4") '("info") (my-project-root)))
(provide 'config-perforce)
