;;; config-keybindings.el --- No Space leader conflict -*- lexical-binding: t; -*-
(defun my-split-below () (interactive) (select-window (split-window-below)))
(defun my-split-right () (interactive) (select-window (split-window-right)))
(defun my-next-window () (interactive) (other-window 1))
(defvar my-window-map (make-sparse-keymap))
(dolist (pair '(("s" . my-split-below) ("v" . my-split-right)
                ("h" . windmove-left) ("j" . windmove-down)
                ("k" . windmove-up) ("l" . windmove-right)))
  (define-key my-window-map (kbd (car pair)) (cdr pair)))
(with-eval-after-load 'evil
  (dolist (map (list evil-normal-state-map evil-motion-state-map
                     evil-visual-state-map evil-insert-state-map))
    (define-key map (kbd "C-e") #'my-treemacs-toggle))
  (define-key evil-normal-state-map (kbd "s") my-window-map)
  (define-key evil-normal-state-map (kbd "SPC") #'my-next-window)
  (dolist (pair '(("C-f" . my-toggle-window-maximize)
                  ("\\" . my-switch-buffer) ("gd" . xref-find-definitions) ("gD" . eglot-find-declaration)
                  ("gr" . xref-find-references) ("gi" . eglot-find-implementation)
                  ("K" . eldoc-print-current-symbol-info) ("za" . hs-toggle-hiding)
                  ("zc" . hs-hide-block) ("zo" . hs-show-block)
                  ("zM" . hs-hide-all) ("zR" . hs-show-all)))
    (define-key evil-normal-state-map (kbd (car pair)) (cdr pair))))
(with-eval-after-load 'treemacs
  (define-key treemacs-mode-map (kbd "C-e") #'my-treemacs-toggle))
(with-eval-after-load 'treemacs-evil
  (evil-define-key 'normal treemacs-mode-map (kbd "C-e") #'my-treemacs-toggle))
(dolist (pair '(("C-e" . my-treemacs-toggle)
                ("C-c p f" . my-project-find-file) ("C-c p s" . my-project-search)
                ("C-c p b" . project-switch-to-buffer) ("C-c p p" . project-switch-project)
                ("C-c p t" . project-shell) ("C-c f r" . my-recent-file)
                ("C-c b" . my-switch-buffer) ("C-c t" . my-treemacs-toggle)
                ("C-c c h" . my-unreal-switch-header-source)
                ("C-c c i" . my-unreal-create-implementation)
                ("C-c w" . whitespace-mode)
                ("C-c c v" . my-cpp-toggle-inline-diagnostics)
                ("C-c c n" . my-cpp-toggle-inlay-hints)
                ("C-c h" . my-dashboard)
                ("C-c c a" . eglot-code-actions) ("C-c c d" . my-cpp-toggle-diagnostics)
                ("C-c c k" . eldoc-print-current-symbol-info) ("C-c u o" . my-unreal-open-project)
                ("C-c u b" . my-unreal-build) ("C-c u e" . my-unreal-build-editor)
                ("C-c v e" . my-p4-edit) ("C-c v r" . my-p4-revert)
                ("C-c v o" . my-p4-opened) ("C-c v d" . my-p4-diff)
                ("C-c v i" . my-p4-info) ("C-c d v" . my-debug-visual-studio)))
  (global-set-key (kbd (car pair)) (cdr pair)))
(provide 'config-keybindings)
