;;; config-dashboard.el --- Small project.el startup screen -*- lexical-binding: t; -*-
(require 'project)
(require 'button)
(require 'seq)
(defcustom my-dashboard-project-limit 10 "Number of known projects to display."
  :type 'integer :group 'my-unreal)
(defcustom my-dashboard-recent-limit 8 "Number of recent files to display."
  :type 'integer :group 'my-unreal)
(defvar my-dashboard-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map special-mode-map)
    (define-key map (kbd "TAB") #'forward-button)
    (define-key map [backtab] #'backward-button)
    (define-key map (kbd "RET") #'push-button)
    (define-key map (kbd "g") #'my-dashboard-refresh)
    map))
(define-derived-mode my-dashboard-mode special-mode "Dashboard"
  "A startup and project landing page made of standard Emacs buttons."
  (setq-local truncate-lines t))
(with-eval-after-load 'evil
  (evil-set-initial-state 'my-dashboard-mode 'emacs))
(defun my-dashboard-button (label action)
  "Insert LABEL as a button calling ACTION without arguments."
  (insert "  ")
  (insert-text-button label 'follow-link t
                      'action (lambda (_button)
                                (if (commandp action) (call-interactively action)
                                  (funcall action))))
  (insert "\n"))
(defun my-dashboard-open-project (root)
  "Open a landing buffer rooted at ROOT, establishing project.el context."
  (let ((project (project-current nil root)))
    (unless project (user-error "No project found at %s; check its markers" root))
    (project-remember-project project)
    (switch-to-buffer (get-buffer-create (format "*Project: %s*" (project-root project))))
    (my-dashboard-mode)
    (setq-local default-directory (file-name-as-directory (project-root project)))
    (my-dashboard-refresh)))
(defun my-dashboard-choose-project ()
  "Choose from project.el's known roots, or register another directory."
  (interactive)
  (let ((roots (project-known-project-roots)))
    (if roots
        (my-dashboard-open-project (completing-read "Open project: " roots nil t))
      (my-dashboard-add-project))))
(defun my-dashboard-add-project ()
  (interactive)
  (my-dashboard-open-project (read-directory-name "Project directory: ")))
(defun my-dashboard-refresh ()
  "Render saved names only: do not stat recent files or scan project contents."
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (insert (propertize "Emacs\n\n" 'face '(:height 1.5 :weight bold)))
    (unless (equal (buffer-name) "*Emacs*")
      (insert (propertize (concat "Project: " default-directory "\n\n") 'face 'font-lock-keyword-face))
      (my-dashboard-button "Find project file" #'my-project-find-file)
      (my-dashboard-button "Search project" #'my-project-search)
      (insert "\n"))
    (insert (propertize "Projects\n" 'face 'bold))
    (let ((roots (seq-take (project-known-project-roots) my-dashboard-project-limit)))
      (unless roots (insert "  No known projects yet. Use Add project below.\n"))
      (dolist (root roots)
        (my-dashboard-button
         (format "%s  —  %s" (file-name-nondirectory (directory-file-name root)) root)
         (lambda () (my-dashboard-open-project root)))))
    (insert (propertize "\nRecent files\n" 'face 'bold))
    (dolist (file (seq-take recentf-list my-dashboard-recent-limit))
      (my-dashboard-button (abbreviate-file-name file) (lambda () (find-file file))))
    (insert (propertize "\nUseful actions\n" 'face 'bold))
    (my-dashboard-button "Open project" #'my-dashboard-choose-project)
    (my-dashboard-button "Add project" #'my-dashboard-add-project)
    (my-dashboard-button "Recent files" #'my-recent-file)
    (my-dashboard-button "Find file" (lambda () (call-interactively #'find-file)))
    (my-dashboard-button "Switch buffer" #'my-switch-buffer)
    (insert "\n  TAB / Shift-TAB: select   RET: open   g: refresh\n")
    (goto-char (point-min))))
(defun my-dashboard-buffer ()
  "Return the startup buffer for `initial-buffer-choice'."
  (with-current-buffer (get-buffer-create "*Emacs*")
    (my-dashboard-mode)
    (my-dashboard-refresh)
    (current-buffer)))
(defun my-dashboard () (interactive) (switch-to-buffer (my-dashboard-buffer)))
(setq initial-buffer-choice #'my-dashboard-buffer)
(provide 'config-dashboard)
