#!/bin/sh

# load $WALLPAPER_IMAGE environment variable
BACKGROUND_IMAGE=~/Wallpapers/737385.jpg

function load_wp(){
    swww img -t any --transition-bezier 0.0,0.0,1.0,1.0 --transition-duration .8 --transition-step 255 --transition-fps 60 $BACKGROUND_IMAGE
}

#perform cleanup and exit
if ! swww query; then
    swww init
fi

load_wp
